### ISSUE TITLE
Problem using embedded resources in web projects

### ISSUE THREAD

**Issue by tdsrhh** [MarcStan/Resource.Embedder#15]
I have a problem using your tool with an ASP.NET ( web form) solution.

I have the resource assemblies embedded ( please see attached image ).

![Case2](https://user-images.githubusercontent.com/40692620/54739973-35cae380-4bba-11e9-8f94-5246a0345e05.png)

But when I run the solution, these embedded resources are not used. 

Do I need some kind of initialization to unpack them ?

**Comment by MarcStan** [comment]
I just created a new WebForms on .Net 4.7.2 project and added translations + resource embedder.

It embedds everything correctly and translations are visible to me.

You don't need to do any initialization as the necessary code is injected during build:

![1](https://user-images.githubusercontent.com/8313404/54772486-59644d00-4bff-11e9-96fd-1462c17b39a7.png)

Can you give a bit more details as per the [issue template](https://github.com/MarcStan/Resource.Embedder/blob/master/ISSUE_TEMPLATE.md) or even a sample to reproduce?

**Comment by MarcStan** [comment]
I tested with a basic WebForms project and it worked.

Feel free to reopen if you can provide more details.

**Comment by tdsrhh** [comment]
He

Please see attached solution I have testet on my web server. When I run it, two labels shows UK text's even if it should show Norwegian texts.

[WebForm1.zip](https://github.com/MarcStan/Resource.Embedder/files/3003904/WebForm1.zip)

Source code 
[WebApplication4.zip](https://github.com/MarcStan/Resource.Embedder/files/3003923/WebApplication4.zip)

I see using JustDecompile that ResourceEmbedderCompilerGenerated is part of the result dll, so I do not understand why it does not uses the embedded language texts.

Regards
Regards

**Comment by MarcStan** [comment]
Thanks for the sample. A few pointers:

`packages.config` does not list the Resource Embedder as a package. Coupled with the two lines below in the csproj it looks like the nuget install process had some issues:
``` xml
<Import Project="C:\TDS\DMZ\Main\TDS.Build.Packages\Resources\1.2.8\build\Resource.Embedder.targets" Condition="Exists('C:\TDS\DMZ\Main\TDS.Build.Packages\Resources\1.2.8\build\Resource.Embedder.targets')" />
..
<Error Condition="!Exists('..\packages\Resource.Embedder.2.0.0\build\Resource.Embedder.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Resource.Embedder.2.0.0\build\Resource.Embedder.props'))" />
```

Essentially your sample is referencing 1.2.8 and error checking that 2.0.0 exists..

Try cleaning that up and reinstalling the 2.0 package again.

___
Beyond that I had a look and saw that you are using `meta:resourceKey` to translate.

When using that you [can't actually set the language in code behind](https://stackoverflow.com/questions/1274406/setting-metaresourcekey-on-page-load) (as the translation is injected before the code gets to run).

The only way to change the culture explicitely is to hardcode it via `<<%@ Page UICulture=".." %>` (or change the browser language).

Otherwise (if you need to set culture in code behind) you will have to use code like this to translate:

``` csharp
protected void Page_Load(object sender, EventArgs e)
{
    Thread.CurrentThread.CurrentUICulture = new CultureInfo(lang);
    Label2.Text = App_LocalResources.Form1_aspx.Label_Text;
}
```

I tested both variants with the resource embedder and both worked.

Here's a sample to repro, let me know if you have any questions.

[WebForms.zip](https://github.com/MarcStan/Resource.Embedder/files/3005025/WebForms.zip)

**Comment by tdsrhh** [comment]
Hi

Thanks for your kind feedback. Your solution works well.

Regards
