### ISSUE TITLE
Debug problem when embedding the assamblys!

### ISSUE THREAD

**Issue by Hendrik-Koelbel** [MarcStan/Resource.Embedder#18]
> Is this the fault of Fody or Resource.Embedder?!

**Expected behaviour**:

The program should embed all dlls and satellite assemblies with every debug no matter if changes have been made or not.

**Actual behaviour:**

The program only embeds all dlls when changes have been made to the program. With multiple debugging without changes to the Windows form, the dlls are no longer embedded but the satellite assemblies are.

**Steps to reproduce the problem:**
First I created a test app to test this and it turned out that this error always occurs.
**[Test App Link](https://github.com/Hendrik-Koelbel/Test_Application)**

 **1. I debug my program and it is perfectly embedded.**

![first_run_good_embedded](https://user-images.githubusercontent.com/31684940/61354720-16e01380-a873-11e9-9105-5bc4d70d372e.png)

  **2. I debug again without having made any changes and it only embeds the language dlls but not the other assemblies like newtonsoft.json.dll or costura.dll**

![second_run_with_failed_embedding](https://user-images.githubusercontent.com/31684940/61354733-1f384e80-a873-11e9-9bff-22b316e5a2b5.png)

  **3. I changed the size of the form or a text and debugged it again. After that everything is properly embedded again.**

![third_run_after_size_change_good_embedded](https://user-images.githubusercontent.com/31684940/61354744-23fd0280-a873-11e9-9530-9d2c4c658786.png)

>**Sometimes a System.BadImageFormatException also appears but this error remains.**

![third_run_this_error_comes](https://user-images.githubusercontent.com/31684940/61356046-d1711580-a875-11e9-9263-ec03d1d9da03.png)

**Details:**

  - .Net Version: v4.7.2
  - Platform/OS Version: Windows 10
  - Additional details: Visual Studio 2019

**Comment by MarcStan** [comment]
Hello,

(I also saw your email but couldn't respond sooner).

There's a few points in your report, so let's go through them one by one:

First off, I can reproduce the error(s) with your sample. Greatly appreciated!
___
> Sometimes a System.BadImageFormatException also appears but this error remains.

You can fix this by upgrading Fody from 5.0.0 to at least 5.0.6 as [reported here](https://github.com/MarcStan/Resource.Embedder/issues/13) to fix that.

I tested your sample application with Fody 5.1.1 and this exception no longer occurs.

___
> I debug again without having made any changes and it only embeds the language dlls but not the other assemblies like newtonsoft.json.dll or costura.dll

I can reproduce this (Costura.dll remains next to exe), **but** by using a tool like [dnSpy](https://github.com/0xd4d/dnSpy) I can also see that Costura.dll is correctly embedded in the exe alongside the resource file as well:

![1](https://user-images.githubusercontent.com/8313404/61477749-40429180-a990-11e9-8c56-b4eccfb51d5e.png)

This also fits together with Fody's build warning "The assembly has already been processed by Fody."

Therefore I would argue that it is a minor bug (only when debugging again without making changes) and that you can always safely copy just the exe and it will work.

## Why is this happening

This is a bit more tricky to answer but it's basically the combination of Fody and Resource.Embedder. Both need to modify the output (exe/dll) after build.

(Copied from an [older issue](https://github.com/MarcStan/Resource.Embedder/issues/13#issuecomment-475437760)):

> ... Visual Studio will either recognize that the code wasn't modified and skip building, or do a clean & rebuild.
> 
> Unfortunately the way my Resource Embedder works, it needs to modify the exe after the Visual Studio build is finished (and has noted the exe state) thus for Visual Studio the exe is always out of sync and Visual Studio wants to build it again (e.g. anytime you want to run it).

This is also the reason you now see the Fody warning.

## Workarounds

* Upgrade to Fody 5.0.6+ and accept that dll's will linger in the output directory when debugging multiple times without making changes
* Downgrade to Fody 3.3.5 or older (to force the usage of Costura <= 3.3.2) (you mentioned in your email that you need newer Fody features, so not an option)

Longterm I hope for [some good stuff](https://github.com/dotnet/coreclr/issues/20287) in .Net Core (this could then make my project obsolete).

Finally regarding your last question from the email:

> Are there other possibilities beside using your Resource.Embedder to include satellite assemblies?

Not that I am aware of, no (hece why I created this package).

But since you are using Winforms, there was a [proposed solution](https://github.com/Fody/Costura/issues/61#issuecomment-61486344) that is Winforms-only that might interest you.

It would have been great to have the Resource.Embedder be a Fody plugin (as suggested in the thread) but Fody runs too early in the pipeline (before the satellite assemblies are generated). At least that was the case back then and I don't think it changed.
