### ISSUE TITLE
Embedded resources are ignored in .Net CLRv2 apps

### ISSUE THREAD

**Issue by AlphaCentaury** [MarcStan/Resource.Embedder#3]
Sample program:
```
private void Form1_Load(object sender, EventArgs e)
{
    label1.Text = Texts.TestString;

    CurrentThread.CurrentUICulture = new CultureInfo("es-es");
    label2.Text = Texts.TestString;

    CurrentThread.CurrentUICulture = new CultureInfo("fr-fr");
    label3.Text = Texts.TestString;
} // Form1_Load
```
where `Form1` is an ordinary Windows Forms with 3 labels and `Texts` is the resource accesor helper created by VS. Resource files are `Texts.resx`, `Texts.es.resx` and `Texts.fr.resx` and contain only one string named `TestString` translated into Spanish and French.

If the target framework is 2.0, 3.0 or 3.5, the program result is as follows
```
DEFAULT
DEFAULT
DEFAULT
```
However, if the target framework is 4 or greater, the output is
```
DEFAULT
Español
Français
```
This also happens with a console app: it runs perfectly under CLR v4 but not under CLR v2. 
```
static void Main(string[] args)
{
    Console.WriteLine(Texts.TestString);

    Thread.CurrentThread.CurrentUICulture = new CultureInfo("es-es");
    Console.WriteLine(Texts.TestString);

    Thread.CurrentThread.CurrentUICulture = new CultureInfo("fr-fr");
    Console.WriteLine(Texts.TestString);
 } // Main
```
Is this a CLRv2 bug? Or a Resource.Embedder bug?

**Comment by MarcStan** [comment]
I can confirm that it does not work.

The problem stems from the fact that the code I inject into the target assembly to load the resources was written in .Net 4.5 (and uses features unavailable in previous versions).

It would also not work on a system with .Net 4.0 installed but not if you updated to [.Net 4.5 (as it replaces .Net 4)](http://www.hanselman.com/blog/NETVersioningAndMultiTargetingNET45IsAnInplaceUpgradeToNET40.aspx).

I will check what can be done about using code available in all platforms, thus making it work for all versions.

**Comment by MarcStan** [comment]
Unfortunately after investigation, this issue seems to be unfixable.
As referred to [here](https://msdn.microsoft.com/en-us/library/system.appdomain.assemblyresolve.aspx).

> **Beginning with the .NET Framework 4**, the ResolveEventHandler event is raised for all assemblies, **including resource assemblies. In earlier versions, the event was not raised for resource assemblies.** If the operating system is localized, the handler might be called multiple times: once for each culture in the fallback chain.

So even if I make my code work with earlier .Net versions it won't execute, because the event I'm using is not being called for resources prior to .Net 4.

**Comment by MarcStan** [comment]
As of [v1.0.8](https://github.com/MarcStan/Resource.Embedder/releases/tag/v1.0.8) the build will now fail with an error if the target project is targeting an older version of .Net (older than .Net 4.0).

Previously it would embed the resource assemblies and then delete the resource assemblies from the disc, but due to the way the ResolveEventHandler worked before .Net 4 it would never be able to load the embedded resources, which meant no localization occured at all for these assemblies.

**Comment by AlphaCentaury** [comment]
Thanks a lot! Great job!
