### ISSUE TITLE
Portable debug information

### ISSUE THREAD

**Issue by clragon** [MarcStan/Resource.Embedder#6]
```bash
MSBUILD : error : portable debug information setting is currently not supported. Once Mono.Cecil 0.10 is out of beta it will be supported. Issue tracked here: https://gitlab.com/MarcStan/Resource.Embedder/issues/8
```

I got this error when I tried to compile my project. It seems as Mono.Cecil 0.10 is out already.
If that is not the case, could you inform me on how to tell my msbuild through a csproj file to not use portable debug information?

thanks in advance

**Comment by MarcStan** [comment]
Yeah I originally intended to update but haven't really gotten around to it. Mainly because Cecil 0.10 switched up some APIs meaning I have to rewrite stuff on my end as well to get it working again.

As quick fix:
On VS 2017, on project properties->build->advanced build settings->debugging information, select full or pdb-only. The project should then build normally.

**Comment by MarcStan** [comment]
It's called "DebugType" from here: https://msdn.microsoft.com/en-us/library/bb629394.aspx so I assume /p:DebugType="full" should work?
Likewise if I set it in my IDE it is actually persistent in my csproj once per build/platform configuration:

``` xml
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <!-- snip -->
    <DebugType>full</DebugType>
  </PropertyGroup>
```

**Comment by clragon** [comment]
Hmm... weird. I added that flag but same error regardless.

**Comment by MarcStan** [comment]
Can you give me more information about your project (.Net version, project type, etc.)?

**Comment by clragon** [comment]
I didnt specify the version so it uses whatever msbuild uses as default,  i assume the newest.
Its a console application. The assembly has 2 dlls which base on each other, while the second dll, that uses the first as dependency, has resource files.
Originally I embeded the dlls with Costura but it fails on mono so I directly tried to compile it all into one file, with no dlls. Problem: my resource files dont get embedded, so thats why i am here. 
When I made an issue on the Costura github i created a new project that has similar specifications like mine ([MonoEmbedFlaws.zip](https://github.com/MarcStan/Resource.Embedder/files/2333381/MonoEmbedFlaws.zip)) if that helps

**Comment by MarcStan** [comment]
I don't think you're doing yourself a favor by not using an IDE with C#.

If you don't like using Visual Studio there are some great cross platform alternatives (Visual Studio Code, Rider) that have decent enough support for C#.

When I loaded your projects into Visual Studio it right away added some stuff to the csproj files, such as:
``` xml
<TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
```
Looking at your precompile binary from the sample in dnSpy also reveals that is was compiled with ".NETFramework,Version=v4.0".

It's been a while since I've worked with Mono, so not sure if it always specifies that value or whether it is infact downgraded due to no specific version being set in the csproj.

Either way, since you seem to have these issues only when using mono, I'll go out on a limb: It might just be that mono always outputs DebugType "portable" since full, etc. are "windows only" and the only way to debug on linux is with portable pdbs..

The last thing you might be able to try is "DebugType=none" but that removes your ability to debug entirely..

If I eventually find the time I'd like to get this project ported to .Net Standard 2 and make sure it works with .Net Core as well. Aong the way I'd also upgrade to Cecil 0.10, but I just don't have the time right now..

**Comment by clragon** [comment]
Yeah, you might be very right, but I decided that the experience of doing so and what I learnt from it was kinda worth it. I plan on porting it into visual studio. I'm currently using visual code, but only as an editor, not at it's full capacity. I'm a beginner in C# and I don't know many things yet, but I think this helped me a bit to understand whats going on under the hood of Visual studio. Having no time? I can relate totally. I barely have time either at the moment. I'll try out the `debugType=None` as soon as I get to it. Thanks for your help. It seems like there are many problems with mono. I've heard that you can enable AOT compile to bypass this and run C# on Linux without it (I need Linux support, no way around it) but I've also heard that it limits the application and besides that I couldn't figure out how to pull it off in msbuild. Google seems like it doesn't wanna tell me how to tell msbuild to compile AOT. mini itself has a flag for it, but msbuild? I got no clue!

**Comment by MarcStan** [comment]
Trying to understand the underlying layers is a great attitute to and will get you very far in software development.

However having worked with C# for a long time I can tell you: MSBuild and the csproj format is not something that is easy to master and not an ideal entry point to C# development. There is a lot of legacy stuff in there and it's best to leave most of the crust to IDEs (infact I know plenty developers who know very little about both and still to generally ok as C# developers).

If you are interested in cross platform development .Net Core is actually a new and great alternative (unless you need UI support, .Net Core can only do web apps and console apps for now).

To get AOT compilation working you will have to use the brand new [CoreRT](https://github.com/dotnet/corert/tree/master/samples/HelloWorld). Unfortunately it is alpha and still lacking a lot of features.

**Comment by clragon** [comment]
That sounds very nice! Too bad it's still in alpha. I for myself are a big fan of single-binary apps because they are handy and portable and ... clean. THey seem less messy and especially for small projects a good idea. I am indeed looking into putting my project on android and making a xaml GUI for it. Would be too bad if that wouldnt be possible, so I'd assume .Net core isnt much of an option, huh? To be honest one day I came up with the principal that having a GUI is neat but the thing is that the person who programmed it does understand it because they built on based on underlying principals and manual processes, which I as a user maybe dont know. So doing it manually will probably help me understanding which way they went and learn me what to search for. Even though I see many people that rely only on GUI for C# and seem to get along fine indeed.  
By the way; My current project is up on [github](https://github.com/clragon/GradeCalc) too. Its kinda messy right now though, because I'm mid-way of redoing things, especially the problem with embedding.
