### ISSUE TITLE
Type.GetType not working!

### ISSUE THREAD

**Issue by ravibpatel** [MarcStan/Resource.Embedder#7]
I am using Resource.Embedder in my project but one of the users reported that it causes Type.GetType to throw FileLoadException exception. I investigated it and found out that removing Resource.Embedder fixes this issue. You can see it at ravibpatel/AutoUpdater.NET#185.

**Comment by MarcStan** [comment]
I found the root cause [here](https://github.com/MarcStan/Resource.Embedder/blob/722ec2cda458ae15353c231f05050c2b23927701/src/ResourceEmbedder.Core/GeneratedCode/InjectedResourceLoader.cs#L35).

When calling "Type.GetType("ArrayOfint, http://schemas.microsoft.com/2003/10/Serialization/Arrays")" I get "http://schemas.microsoft.com/2003/10/Serialization/Arrays" as the assembly name passed into new AssemblyName.

IMO this is not a valid format, but I should be doing user input validation regardless.

**Comment by MarcStan** [comment]
I've added the required input validation to [1.2.6](https://www.nuget.org/packages/Resource.Embedder/)

**Comment by ravibpatel** [comment]
@MarcStan Thanks for the fast update. I will check it out.
