### ISSUE TITLE
The "ResourceEmbedder.MsBuild.SatelliteAssemblyEmbedderTask" task failed unexpectedly

### ISSUE THREAD

**Issue by LaroCroft** [MarcStan/Resource.Embedder#8]
Getting this error on building the exe with embedded assemblies

Any ideas? I have another project with the same error but there is disappeared after killing msbuild.exe

System.IO.IOException: The process cannot access the file '...\obj\x86\Debug\SwyxMetaServices.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at ResourceEmbedder.Core.Cecil.CecilBasedAssemblyModifier.Save() in C:\Projects\Resource.Embedder\src\ResourceEmbedder.Core\Cecil\CecilBasedAssemblyModifier.cs:line 150
   at ResourceEmbedder.Core.Cecil.CecilBasedAssemblyModifier.Dispose() in C:\Projects\Resource.Embedder\src\ResourceEmbedder.Core\Cecil\CecilBasedAssemblyModifier.cs:line 123
   at ResourceEmbedder.MsBuild.SatelliteAssemblyEmbedderTask.Execute() in C:\Projects\Resource.Embedder\src\ResourceEmbedder.MsBuild\SatelliteAssemblyEmbedderTask.cs:line 121
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by MarcStan** [comment]
There [was an issue](https://github.com/MarcStan/Resource.Embedder/issues/2) early on where msbuild locked the obj files, but it has long been fixed.

Can you try what is [suggested here](https://github.com/MarcStan/Resource.Embedder/issues/1) (essentially building with "/nr:false") and see if that helps?

Also do you have some more details about your project?
What platform/.Net Version is it targeting, what type of project is it (WPF, Windows Service, ....)?

**Comment by LaroCroft** [comment]
I've set MSBuildDisableNodeReuse=1 as environment variable.
Is this correct or is there any other thing to do? Problem still persists...

**Comment by LaroCroft** [comment]
Btw...
.Net Version is 4.5.1. Project is a windows service / console app. Nothing special. Weird thing I've another project where it's working. Also a service with the same architecture.

**Comment by MarcStan** [comment]
The environment variable should be enough (although Visual Studio must be restarted for it to take effect).

Can you provide a sample project where I can reproduce?

**Comment by LaroCroft** [comment]
Sure, I restarted Visual Studio after setting the variable.
I checked in Task Manager. When I start build I see 2 MsBuild. exe in Task Manager. One using CPU the other one doesn't?! After build both processes terminate. They remained in Task Manager before setting the value.
But the error message remains. 
Providing a sample project might be difficult. It's a rather large project with some dependencies.
Is there any way to trace something?

**Comment by MarcStan** [comment]
MsBuild will start processes based on the processor count and will attempt to build in parallel.

Sounds like you have two cores and msbuild wasn't able to parallelize anything, nothing unusual here.

Since you mentioned two projects (one where it's working and one where it isn't) you could perhaps try to figure out the differences between the two projects (to narrow down what the root cause could be)?

Otherwise there isn't really anything built in to help me trace it without a repro sample.
But you are of course free to debug yourself.

___
You can just call SatelliteAssemblyEmbedderTask using the correct parameters.

- ProjectDirectory (full path to the folder of your csproj)
- AssemblyPath (full path to the exe/dll to be modifed inplace)
- TargetPath (full path of exe/dll)
- BuildEngine (any instance will do, e.g. I use NSubstitute.Substitute.For<IBuildEngine>() in my tests)
- References (comma seperated list of directories where to look for the references)

The list of References you can get from the Visual Studio Output window during the regular build when Resource.Embedder is used (there should be a line "Looking for references in: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5, ... etc"). Copy those **and be sure to use ";" instead of ","** when setting it to the References property in code or it won't resolve correctly.

Also see the test "MsBuildBasedEmbedding" inside "FullMsBuildTests.cs" which you can probably use as a base to start with.

Final note: The replacement of the exe/dll happens inplace (meaning you will have to copy/rebuild it everytime as it is changed), my test setup usually involves having the dll/exe elsewhere and having it copied to the location where it is modifed.

I hope this helps you to look in the right direction, feel free to ask for more details if needed.

**Comment by LaroCroft** [comment]
Sorry, my last message didn't get posted here :-(
I figured out that it's my dropbox sync in the background prevents the build from completing. Since I stopped that service or excluded the bin / obj folders everything is working. 
Weird why it worked with the other project but not with this one :-|

Anyway... Thx for your great support
