### ISSUE TITLE
Resources embedded only after "after build" Tasks.

### ISSUE THREAD

**Issue by EaranMaleasi** [MarcStan/Resource.Embedder#9]
I just wanted to automate a process by using the "after build" event in VS, where the files, after successful build get copied to another directory. I was surprised to see, that the copied files still included the satellite assemblies and after looking into the build log, I found that everything in "after build" was executed before ResourceEmbedder. 

**Expected behaviour:**
Satellite assemblies are embedded into the executable before "after build" tasks are executed

**Actual behaviour:**
Satellite assemblies are embedded after all "after build" tasks are finished.

**Supposed fix:**
Somehow enable the user to define when ResourceEmbedder does its wonderful magic.

I really don't know how this embedding magic works or even the details of what VS does when I hit "build" therefore I don't know if this is even possible. If not, I'm just grateful that this exists and saves me the time to read the Fody/Costura manual every time I want to embed the resource assemblies.

**Comment by MarcStan** [comment]
First of all: Great report! I really like the format!

I had a look and the fix was quite easy.

First of all, I was already embedding the satellite assemblies very early in the build process, however the cleanup was ran as "after AfterBuild", thus why your AfterBuild steps still copied the resource files.

I simple moved it to ["before AfterBuild"](https://github.com/MarcStan/Resource.Embedder/blob/4b85104ed238d5801844edd56b38741259227648/src/ResourceEmbedder.MsBuild/Resource.Embedder.targets#L23). This should mean you should now no longer see the files during AfterBuild targets!

I uploaded v1.2.7 with the change, let me know if it isn't working correctly.

**Comment by EaranMaleasi** [comment]
The Cleanup still takes place after the 'After Build' Tasks. I Cleaned the project, deleted the NuGet, restarted VS (2017 Enterprise) and added the NuGet Package again.

 Looking into the Build Log I see this:  
```
1>  Looking for references in: C:\PathToBinFolder C:\PathToLocalReference, C:\PathToProjectFolder, C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0
1>  Rewritting pdb
1>  Finished embedding cultures: de into MyProgram.exe in 74ms
.
.
.
Whatever the After Build Tasks write into the log
.
.
.
1>  Deleted resource file 'de' as it was embedded into the target.
1>  Deleted resource directory 'de' as it is empty.
```

Before, I just assumed that everything was done after the "After Build" Tasks , but now knowing that the actual embedding takes place before the "AfterBuild" Tasks, I could simply Ignore the resource directory later on, or even delete it myself as a workaround.

However, if I can show you something, or if I should do something that helps you finding out why this doesn't work for me, I'll gladly help.

**Comment by EaranMaleasi** [comment]
I've just noticed a big mistake on my part, what I meant is **PostBuild** and not AfterBuild. 
I am so sorry. I thought the two were the same, when in fact PostBuild Events are executed before AfterBuild Tasks.

**Comment by MarcStan** [comment]
Yes, they are indeed different steps.

I'll have a look if I can execute my code before the PostBuild event, but it will need more testing because PostBuild doesn't always run e.g. you can configure to run it only on successful builds/always/etc..

I want to make sure the change doesn't break any of those scenarios.

**Comment by MarcStan** [comment]
I published a [beta version](https://www.nuget.org/packages/Resource.Embedder/1.2.8-beta.1) which I think will work for you now as cleanup runs before PostBuild now.

Can you try it out for me? If it works, I'll finalize the package.

**Comment by EaranMaleasi** [comment]
Works like a charm:
```
1>  Looking for references in: C:\PathToBinFolder C:\PathToLocalReference, C:\PathToProjectFolder, C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0
1>  Rewritting pdb
1>  Finished embedding cultures: de into MyProgram.exe in 74ms
1>  Rewritting pdb
1>  Finished embedding cultures: de into MyProgram.exe in 331ms
1>  MyProgram-> C:\PathToBinFolder\MyProgram.exe
1>  CleanupBeforePostBuild
1>  Deleted resource file 'de' as it was embedded into the target.
1>  Deleted resource directory 'de' as it is empty.

PostBuild logs
```
Thank you very much.

**Comment by MarcStan** [comment]
Happy to help!

1.2.8 is now live as well.
